### ISSUE TITLE
support spliting a gesture into multiple actions

### ISSUE THREAD

**Issue by pguedes** [pguedes/gesticle#7]
for example, when zooming currently we execute one action at the **end** of the full gesture e.g. ctrl+ . 
It would be cool if we could say that every `some variation of the pinch gesture` execute one ctrl+

**Comment by Alsan** [comment]
Do you mean combining multimple action keys (like `swipe.left.3 = mod1+key1;mod2+key2`), or joining multiple gestures as one gesture, just like the 'L' shape gesture? Or you want to inherit the behavior from the parent? Would you please explain more about the use case?

**Comment by pguedes** [comment]
I meant executing an action multiple times instead of just once when the gesture is done. 

For example: currently when I want to zoom three times (like 3x `Ctrl+` on my browser) I will do the pinch 3x... but I think a better way would be to trigger the `Ctrl+` at every `x` pinch variation (a certain amount of the pinch gesture, in distance of fingers?) Like what tablets and phones do nowadays... I think it's more natural

**Comment by Alsan** [comment]
Good point, but as my personal perference, zoom is a continuous action, and should be bind to every pinch update action. I'll try to implement this later these two days.
